### PR TITLE
feat: strip paragraphs option

### PR DESCRIPTION
**Pull request by nobkd**
### Description

This PR introduces an option to strip / not strip paragraphs from MDC block slots.

### CODE REVIEW

**Comment by nobkd** [comment]
Oh. Just because I noticed it, [`remark-mdc`](https://github.com/nuxtlabs/remark-mdc?tab=readme-ov-file#use) has paragraphs **not stripped** by default.

<details>
<summary>Show code</summary>

**`package.json`**

```json
{
  "name": "test-paragraph-stripping-remark-mdc",
  "version": "0.0.0",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "dev": "node index.js"
  },
  "devDependencies": {
    "remark-mdc": "^2.0.0",
    "remark-parse": "^10.0.2",
    "unified": "^11.0.3",
    "util": "^0.12.5"
  }
}
```

**`index.js`**

```js
import { unified } from 'unified';
import parse from 'remark-parse';
import remarkMDC from 'remark-mdc';
import util from 'util';

function compiler() {
  this.Compiler = function(root) {
    return root;
  }
}

async function markdownToAST(markdown) {
  let stream = unified()
    .use(parse)
    .use(remarkMDC)
    .use(compiler);

  const file = await stream.process(markdown);
  return file.result;
}

console.log(util.inspect(await markdownToAST('::component-name\nparagraph one.\n\nparagraph two.\n::'), {showHidden: false, depth: null, colors: true}))
```

</details>

---

<details>
<summary>Show result</summary>

```js
{
  type: 'root',
  children: [
    {
      type: 'containerComponent',
      name: 'component-name',
      attributes: {},
      children: [
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              value: 'paragraph one.',
              position: {
                start: { line: 2, column: 1, offset: 17 },
                end: { line: 2, column: 15, offset: 31 }
              }
            }
          ],
          position: {
            start: { line: 2, column: 1, offset: 17 },
            end: { line: 2, column: 15, offset: 31 }
          }
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              value: 'paragraph two.',
              position: {
                start: { line: 4, column: 1, offset: 33 },
                end: { line: 4, column: 15, offset: 47 }
              }
            }
          ],
          position: {
            start: { line: 4, column: 1, offset: 33 },
            end: { line: 4, column: 15, offset: 47 }
          }
        }
      ],
      position: {
        start: { line: 1, column: 1, offset: 0 },
        end: { line: 5, column: 3, offset: 50 }
      },
      data: { hName: 'component-name', hProperties: {} },
      fmAttributes: {}
    }
  ],
  position: {
    start: { line: 1, column: 1, offset: 0 },
    end: { line: 5, column: 3, offset: 50 }
  }
}
```

</details>

**Comment by nobkd** [comment]
It would be great to have more granular control, but I would like it as an addition to a global default.

Maybe something similar to the `unwrap` option of [`nuxt-mdc`](https://github.com/nuxt-modules/mdc)s [`MDCSlot`] (https://github.com/nuxt-modules/mdc/blob/main/src/runtime/components/MDCSlot.vue)?

**Comment by Atinux** [comment]
I have been talking to Ahad about this and I believe we should unwrap by default if the content inside the component contains only one parent.

This gives the possibility to leverage only `<slot>` for components to be compatible with other data sources and avoid the usage of custom components such as `<MDCSlot>` (which is not possible when using `markdown-it`)

We also discussed about the ability to unwrap directly inside at the slot level:

```md
::my-component
#default{unwrap="p"}
My content unwrapped
::
```

**Comment by nobkd** [comment]
Moved to different branch and therefore autoclosed.

**Pull request closed without merging**
